---
title: "Assignment 5"
author: "Tyanna Bui"
date: "11/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# loading tidyverse
library(tidyverse)
library(car)
library(kableExtra)
library(ggpubr)
library(effsize)
library(stargazer)


# loading csv files
faculty_salary = read_csv("Faculty salary data (2008 - 2009 survey).csv")
grad_enroll = read_csv("Grad enrollment 1967 - 2015.csv")
med_salary = read_csv("Median salary for doctoral recipients.csv")
phd = read_csv("PhDs by Field 1985 - 2015.csv")
```


#### Part 1
```{r}
# full time enrollment dataset
full_enroll = select(grad_enroll, year, full_time_men, full_time_women)

# part time enrollment dataset
part_enroll = select(grad_enroll, year, part_time_men, part_time_women)

# total enrollment dataset
total_enroll = select(grad_enroll, year, total_men, total_women)


# plotting full & part time enrollment
plot_enroll = ggplot(full_enroll, aes(x = year, y = full_time_men)) +
  geom_line(color = 'red') +
  geom_line(data = full_enroll, aes(x = year, y = full_time_women), color = 'pink') +
  geom_line(data = part_enroll, aes(x = year, y = part_time_men), color = 'blue') +
  geom_line(data = part_enroll, aes(x = year, y = part_time_women), color = 'lavender') +
  theme_classic() +
  labs(x = "Year", y = "Amount Enrolled in Graduate School", title = "Female and Male Enrolled in Graduate School Part-time and Full-time \n(1967 - 2015)") 
# need to add legend
# Viewing plot
plot_enroll


# total enrollment dataset & plotting (USING)
total_enroll = select(grad_enroll, year, total_men, total_women)
plot_total_enroll = ggplot(total_enroll, aes(x = year, y = total_men)) +
  geom_point(color = 'cornflowerblue') +
  geom_point(data = grad_enroll, aes(x = year, y = total_women), color = 'pink') +
  theme_pubr() + 
  geom_smooth(method = lm, se = TRUE, size = 0.5, aes(y = total_women, x = year, color = "Female")) +
  geom_smooth(method = lm, se = TRUE, size = 0.5, aes(y = total_men, x = year, color = "Male")) +
  labs(x = "\nYear", y = "Amount Enrolled in Graduate School\n") +
  scale_color_manual(name = "Gender", values = c("Female" = "pink", "Male" = "blue")) +
  scale_x_continuous(breaks = seq(1965, 2020, by = 10))
#HOW THE HECK DO I MAKE THE LEGEND!! Dx
# Viewing plot
plot_total_enroll

# Linear regression for females & males
female_lm = lm(total_women ~ year, data = total_enroll)
male_lm = lm(total_men ~ year, data = total_enroll)
summary(female_lm)
summary(male_lm)


```


#### Part 2
```{r}

phd_PSES <- phd %>%
  filter(`f_s` == "PSES_Female" | `f_s` == "PSES_Male") %>% 
  select(-f_s) %>% 
  select("1985", "2000", "2015")

rownames(phd_PSES) <- c("PSES_Male", "PSES_Female")
phd_PSES <- t(phd_PSES)
phd_PSES1 <- data.matrix(phd_PSES)
PSES_prop <- prop.table(phd_PSES1, 1)
PSES_x2 <- chisq.test(phd_PSES1)
PSES_x2

phd_Engi <- phd %>%
  filter(`f_s` == "Engi_Female" | `f_s` == "Engi_Male") %>% 
  select(-f_s) %>% 
  select("1985", "2000", "2015")

rownames(phd_Engi) <- c("Engi_Male", "Engi_Female")
phd_Engi <- t(phd_Engi)
phd_Engi1 <- data.matrix(phd_Engi)
Engi_prop <- prop.table(phd_Engi1, 1)
Engi_x2 <- chisq.test(phd_Engi1)
Engi_x2

phd_Edu <- phd %>%
  filter(`f_s` == "Edu_Female" | `f_s` == "Edu_Male") %>% 
  select(-f_s) %>% 
  select("1985", "2000", "2015")

rownames(phd_Edu) <- c("Edu_Male", "Edu_Female")
phd_Edu <- t(phd_Edu)
phd_Edu1 <- data.matrix(phd_Edu)
Edu_prop <- prop.table(phd_Edu1, 1)
Edu_x2 <- chisq.test(phd_Edu1)
Edu_x2

phd_HA <- phd %>%
  filter(`f_s` == "HA_Female" | `f_s` == "HA_Male") %>% 
  select(-f_s) %>% 
  select("1985", "2000", "2015")

rownames(phd_HA) <- c("HA_Male", "HA_Female")
phd_HA <- t(phd_HA)
phd_HA1 <- data.matrix(phd_HA)
HA_prop <- prop.table(phd_HA1, 1)
HA_x2 <- chisq.test(phd_HA1)
HA_x2


```

```{r}
phd_plot <- phd %>% 
  filter(`f_s` == "PSES_Female" |
           `f_s` == "Engi_Female" |
           `f_s` == "Edu_Female" |
           `f_s` == "HA_Female"
         ) %>% 
  gather("Year", "Count", 2:8)
phd_plot$Year <- as.numeric(phd_plot$Year)

phd_plot$f_s <- factor(phd_plot$f_s, levels=c("PSES_Female", "Engi_Female", "Edu_Female", "HA_Female"), labels=c("Physical and Earth Sciences", "Engineering", "Education", "Humanities & Arts"))

phd_plt <- ggplot(phd_plot) +
  geom_line(aes(x = Year, y = Count, color=f_s)) +
  theme_pubr() +
  labs(color = "Field", x = "\nYear", y = "Female PhD Recipients\n")+
  scale_x_continuous(breaks = seq(1985, 2020, by = 5))
  

phd_plt
```


```{r}
#COMPRISION 2

phd_2 <- phd %>%
  filter(`f_s` == "PSES_Female" | `f_s` == "Engi_Female" |`f_s` == "Edu_Female" |`f_s` == "HA_Female" ) %>% 
  select("1985", "2000", "2015")

rownames(phd_2) <- c("PSES", "Engi", "Edu", "HA")
phd_2 <- t(phd_2)
phd_2 <- data.matrix(phd_2)
phd_prop <- prop.table(phd_2, 1)
phd_x2 <- chisq.test(phd_2)
phd_x2

```

```{r}

phd_3 <- phd %>%
  filter(`f_s` == "PSES_Female" | `f_s` == "Engi_Female" |`f_s` == "Edu_Female" |`f_s` == "HA_Female" ) %>% 
  select(-f_s)

rownames(phd_3) <- c("PSES", "Engi", "Edu", "HA")
phd_3 <- t(phd_3)
phd_3 <- data.matrix(phd_3)
phd3_prop <- prop.table(phd_3, 1)
phd3_prop <- t(phd3_prop)
phd3_prop <- as.data.frame(phd3_prop)

phd3_prop <- mutate(phd3_prop, Field = c("Physical and Earth Sciences", "Engineering", "Education", "Humanities & Arts"))
phd3_prop <- gather(phd3_prop, "Year", "Count", 1:7)
phd3_prop$Year <- as.numeric(phd3_prop$Year)

phd_plt2 <- ggplot(phd3_prop) +
  geom_line(aes(x = Year, y = Count, color=Field)) +
  theme_pubr() +
  labs(color = "Field", x = "\nYear", y = "Female PhD Recipients Proportion\n")+
  scale_x_continuous(breaks = seq(1985, 2020, by = 5)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.1))
  

phd_plt2

```

#### Part 3
```{r}
#Null Hypothesis: Ranks are equal
#Alternative Hypothesis: Ranks are NOT equal
median_pd <- wilcox.test(med_salary$men_postdoc, med_salary$women_postdoc, paired = TRUE)
median_pd
#p-value is more than 0.05--retain the null hypothesis
#There is no significant difference in postdoc salary between men and women

#Null Hypothesis: Ranks are equal
#Alternative Hypothesis: Ranks are NOT equal
median_npd <- wilcox.test(med_salary$men_employment, med_salary$women_employment, paired = TRUE)
median_npd

table_salary <- read_csv("median_doctoral_salary.csv")

coh_pd <- cliff.delta(med_salary$men_postdoc, med_salary$women_postdoc)
coh_pd

coh_npd <- cliff.delta(med_salary$men_employment, med_salary$women_employment)
coh_npd
#p-value is less than 0.05--retain the null hypothesis
#There is a significant difference in employment salary between men and women

#Graph

doc_salary <- table_salary %>% 
  mutate(postgrad_plan = ifelse(postgrad_plan == "Employment", "Non-Postdoctoral", "Postdoctoral"))

graph_salary <- ggplot(doc_salary, aes(x= factor(field,levels = rev(levels(factor(field)))), y = salary)) +
  geom_col(aes(fill = sex), position = "dodge") +
  facet_wrap(~postgrad_plan) +
  theme_classic() +
  labs(x = "Subject", y = "Median Salary ($)") +
scale_x_discrete(expand = c(0,0),limits = rev(levels(doc_salary$field))) +
  scale_y_continuous(expand = c(0,0)) +
  coord_flip() +
  labs(x = "") +
  theme(panel.spacing = unit(2, "lines")) +
  scale_fill_manual(values=c("pink","skyblue")) +
  guides(fill=guide_legend(title="Sex"))
  
graph_salary

```


### Part 4
```{r}

by_rank <- ggplot(faculty_salary, aes(x = salary)) +
  geom_density(aes(color = faculty_rank, fill = faculty_rank), alpha = 0.3)

by_rank
prof_salary <- filter(faculty_salary, faculty_rank == "Prof")

by_sex_prof <- ggplot(faculty_salary, aes(x = salary)) +
  geom_density(aes(color = sex, fill = sex), alpha = 0.3)

by_sex_prof

by_phd_grad <- ggplot(faculty_salary, aes(x = years_since_PhD, y = salary))+
  geom_point(aes(color = discipline, shape = sex))+
  facet_wrap(~faculty_rank)
  
by_phd_grad

by_fac_year <- ggplot(faculty_salary, aes(x = years_faculty_service, y = salary))+
  geom_point(aes(color = discipline, shape = sex))+
  facet_wrap(~faculty_rank) 
by_fac_year
```



```{r}

salary_lm1 <- lm(salary ~ faculty_rank + discipline + years_since_PhD + years_faculty_service + sex, data = faculty_salary)

summary(salary_lm1)

vif(salary_lm1)

```

```{r}

salary_lm2 <- lm(salary ~ faculty_rank + discipline + years_faculty_service + sex, data = faculty_salary)

summary(salary_lm2)

vif(salary_lm2)

```

```{r}

salary_lm3 <- lm(salary ~ faculty_rank + discipline + years_since_PhD + sex, data = faculty_salary)

summary(salary_lm3)

vif(salary_lm3)

```

```{r}
AIC(salary_lm1)
AIC(salary_lm2)
AIC(salary_lm3)
```

```{r, results='asis'}
lm_table <- stargazer(salary_lm3, type = "html")
```

